### ISSUE TITLE
Support an automatic and full file sync

### ISSUE THREAD

**Issue by IPWright83** [Genuitec/CodeTogether#234]
**Is your feature request related to a problem? Please describe.**
Often when pairing (or mob programming) you want to be able to execute code, run tests etc while someone else is writing code. Additionally sometimes if working closely with someone you want to keep keep touching base on where you've got too without having to constantly carry out git merges.

**Describe the solution you'd like**
I'd like your tool to offer a full file system synchronization, such that each user has a full local copy that keeps in step with changes. This would allow for build tools/tests to be run, clients could run/debug code etc. You'd even be able to use tools that use file watchers to automate hit reloading etc if another client makes a change.

**Describe your primary environment**
Typically 2-6 clients with a mix of editors/IDEs (Sublime Text/VSCode/IntelliJ)

**Describe alternatives you've considered**
I've used the only tool that I know works using the suggested model with great success but I think the company is on a long wind down (Floobits).

**Additional context**
This would remove the need for features like https://github.com/Genuitec/CodeTogether/issues/227 because each client could have their own web server.

**Comment by wgalanciak** [comment]
@IPWright83 , thanks for sharing the idea!

The concept that you describe is more close to the one where a central role plays a shared remote workspace, instead of the host, and all changes are synced across all participants in real-time through it.

When we have started to work on CodeTogether, we considered several different approaches, including similar to the one above. Eventually, we came up with an idea to make clients completely independent from the technologies used by the shared project(s). It gave us the ability to move responsibility for how and what you can do to the host. One of the main benefits is that you can connect from any client, including a browser (which was the only way to connect until we introduced IDEs clients in 3.0). The client's IDE does not need to be configured and support all a given language or technology. You do not need to build the project on your side. You do not need to setup anything and instead just join and start coding together.

Although we are still actively working on some of the features, including the ability to run tests or debug, the main concept is not going to be changed. I hope that even if the current form of CodeTogether does not fulfill all your needs, it is still useful for you and helps in your day to day coding.

**Comment by IPWright83** [comment]
Thanks for your feedback @wgalanciak . I've not actually tried CodeTogether, I was responding to a Twitter message suggesting it when I was trying to contact Floobits.

Unfortunately there are a number of tools that work with the single "host" approach but as far as I can see only 1 with the full sync approach. I'll keep pressing Floobits to open source instead :)
