### ISSUE TITLE
[Intellij 2019.2] "No file is currently selected for collaboration"

### ISSUE THREAD

**Issue by TybaIt** [Genuitec/CodeTogether#261]
For some reason I cannot select a file.

Others always see no file selected.

However, for some reason they see the error log and see where a syntax error is.

**Comment by brianvfernandes** [comment]
@TybaIt the first thought I have is that this file is somehow not "in your workspace". While we do support external files, perhaps this is a case we have not covered. 

- Could you tell us what type of file this is and what editor it is open in? 
- Can you share any details on the project type and structure? Are you using modules, is this file local, or on a network share, etc.
- Have you tried opening other file types, like a simple text file?
- Could you tell me how your colleagues connected to the session, did they connect from IntelliJ too or did they use a browser to join? 
- What version of the CodeTogether plugin do you have installed?

**Comment by TybaIt** [comment]
> Could you tell us what type of file this is and what editor it is open in?  

It's a Maven project with .xhtml files. All locally available and inside the workspace (ie.the project.)  

> Can you share any details on the project type and structure? Are you using modules, is this file local, or on a network share, etc.
Have you tried opening other file types, like a simple text file?  

I host the session and it creates a border around my open file tab. It becomes green so it should be hosted. But only the error log shows up.  

> Could you tell me how your colleagues connected to the session, did they connect from IntelliJ too or did they use a browser to join?  

I sent them the provided session link. I also tried joining myself with the browser (having my IntelliJ host open and the browser to check out the error myself.)  

> What version of the CodeTogether plugin do you have installed?  

Version 3.2.0-00766

**Comment by brianvfernandes** [comment]
Thanks for the quick reply, we appreciate it!
- Can you let us know what distribution of IntelliJ you're using? WebStorm, IDEA, etc.?
- While you mentioned a number of file types, it wasn't clear what file you are actually trying to open, or perhaps you tried all types? Do you mind checking an actual .txt file? For context, we're asking specifically because we're not sure what editor is in use, and whether that might be a problem.
- As a host, can you check IntelliJ's error log to see if there are any CodeTogether specific errors? If there are, can you paste them here? You can find the error log using the Help > Show Log in Explorer menu item in IntelliJ.

**Comment by TybaIt** [comment]
> Can you let us know what distribution of IntelliJ you're using? WebStorm, IDEA, etc.?
IDEA

> While you mentioned a number of file types, it wasn't clear what file you are actually trying to open, or perhaps you tried all types? Do you mind checking an actual .txt file? For context, we're asking specifically because we're not sure what editor is in use, and whether that might be a problem.

We tried *.java and *.xhtml

Also tried with a text files just now. Same problem.

> As a host, can you check IntelliJ's error log to see if there are any CodeTogether specific errors? If there are, can you paste them here? You can find the error log using the Help > Show Log in Explorer menu item in IntelliJ.

[idea.log](https://pastebin.com/raw/24nJQQdC)

**Comment by brianvfernandes** [comment]
I must admit we're flummoxed - your use case appears to be pretty straightforward and unfortunately the log file contains no more information. Did you try switching things around with your colleagues hosting instead of you? Or have you tried hosting any other projects? If you can spare about 30 minutes, we'd love to get on a video call with you and see the problem first hand - do let us know!

**Comment by TybaIt** [comment]
A colleague tried to host and the same problem persists.
Sure we can go on a video call. Best this weekend evening 6pm or 7pm Central European Time. Just tell me if today (Friday), Saturday. Sunday works too if schedule doesn't allow the other days.

**Comment by wgalanciak** [comment]
This is my time zone so let me take over this issue from Brian. Please send an e-mail to support@codetogether.com so we will be able to exchange meeting details privately.

**Comment by wgalanciak** [comment]
Ok, so we found out what was the root cause of the issue. Accidently, someone added parentheses to the project name. After removing them session works fine.

**Comment by wgalanciak** [comment]
FYI, opened a dedicated issue (#262) to track work on it.
