### ISSUE TITLE
Add Open VSX to Download Page

### ISSUE THREAD

**Issue by brianking** [Genuitec/CodeTogether#281]
Issue #10 added your VS Code extension to the Open VSX Registry. 

This issue is to request that Open VSX is listed as one of the options on the download page:
https://www.codetogether.com/download/

A growing number of companies are adopting Open VSX, some of which are listed at:
https://ecdtools.eclipse.org/adopters/

**Comment by toddewilliams** [comment]
Excellent idea Brian. Open-VSX has been supported since our first release and is mentioned on a couple of the other pages, but not on the download page.

Here’s the link for anyone that needs it before we can update the download page:
[CodeTogether from open-vsx.org](https://open-vsx.org/extension/genuitecllc/codetogether)

**Comment by wgalanciak** [comment]
@brianking, Open VSX link is now available on our download page.

**Comment by brianking** [comment]
Good to hear, thanks for the prompt fix!
