### ISSUE TITLE
Add context menu for Open Declaration/Go To Definition in Eclipse as a client

### ISSUE THREAD

**Issue by toddewilliams** [Genuitec/CodeTogether#322]
**Is your feature request related to a problem? Please describe.**
There are no "Open Declaration / Go To Definition" entries on the context menu when using Eclipse as a client.

**Describe the solution you'd like**
When using Eclipse as a client, it would be great if the context menu had the normal "Open Declaration / Go To Definition" entries that an Eclipse user would expect.

**Comment by TimWebb** [comment]
Due to complexities with the lazy nature of the language service, I'm removing this card from consideration at the time. It feels inconsistent having the Open Declaration action always active despite the fact that for many blocks of code, the action does not make semantic sense. Users can work with F3 or control-click to open declaration where appropriate.
