### ISSUE TITLE
Eclipse Join Remote Session not available on Version 4.25

### ISSUE THREAD

**Issue by Sleinmaster** [Genuitec/CodeTogether#397]
**Describe the bug**
When pressing Join Remote Session in Eclipse I get a message, that it's not compatible with this version of Eclipse.

**To Reproduce**
1. go to CodeTogether View
2. Press Join Remote Session
3. Error pops up

**Expected behavior**
Joining remote Session is possible

**Screenshots**
![image](https://user-images.githubusercontent.com/79196358/196871366-861e8bd1-2b86-4af8-a59a-fc6e419abe28.png)
![image](https://user-images.githubusercontent.com/79196358/196871463-2b15db94-3f47-43f0-998f-37a6ff8063df.png)

**IDE Participant**
 - IDE: Eclipse
 - IDE Version 4.25.0 (2022-03)
 - OS: Windows
 - OS Version: 10

**Comment by Sleinmaster** [comment]
There was apparently something wrong with my eclipse installation

**Comment by ChristianHuff-DEV** [comment]
I am facing the same issue. Could you pinpoint what exactly was wrong with your installation?

**Comment by Sleinmaster** [comment]
I have no Idea what was wrong, I uninstalled Eclipse and reinstalled it, and then it worked.

**Comment by difflaender** [comment]
One possible cause I noticed was that this issue appears when running Eclipse with a custom JDK (in our case an Eclipse Adoptium distribution with some additional certs) instead of the built-in JustJ JRE.

No clue why exactly that is a problem that prevents us from joining sessions from Eclipse while still being able to host sessions in Eclipse.

**Comment by difflaender** [comment]
In case anyone else runs into this issue: The customer support helped us figure out that this issue can occur when using a JDK 11 to run Eclipse. Apparently there has been a change in of the recent CodeTogether plugin versions and one of its dependencies is now relying on Java 17 features. So upgrading the Eclipse JDK version to 17 fixed the issue for us.

**Comment by toddewilliams** [comment]
Thank you for the follow-up to help others @difflaender. We appreciate it and upgrading to JDK 17 will indeed fix the issue for the latest versions of Eclipse.

However, in order to be comprehensive, JDK 11 can still be used to run older versions of Eclipse with CodeTogether, if required. Here is the complete rundown from our support team:

```
For the Java 11 + Eclipse issue: 
As of Eclipse 2022-09, some TextMate support plugins that we depend on when Eclipse is 
used as a client require Java 17. The error message is definitely misleading and will be 
corrected - sorry you had to spend so much time narrowing it down.

Unfortunately, there's nothing we can do about this dependency - you will have to run 2022-09 with Java 17.
However, if you must use Java 11, you will have to use Eclipse 2022-06 or older, 
where the minimum required Java version was still Java 11.
```
